# Generated by Django 3.2.6 on 2022-04-28 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('vacine', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('batch', models.CharField(max_length=100)),
                ('vaccinator', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('complete', models.BooleanField()),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.sprint')),
            ],
        ),
    ]
